name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        KINOPOISK_API_KEY: ${{ secrets.KINOPOISK_API_KEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        KINOPOISK_API_KEY: ${{ secrets.KINOPOISK_API_KEY }}
        BRANCH: gh-pages
        FOLDER: dist
